"""
py_mind_memo の定数定義
"""

# 画像関連
MAX_IMAGE_WIDTH = 200
MAX_IMAGE_HEIGHT = 200
IMAGE_SPACING = 10

# エディタ関連
EDIT_WINDOW_MIN_WIDTH = 200
EDIT_WINDOW_PADDING_X = 50
EDIT_WINDOW_HEIGHT_BASE = 100
EDIT_WINDOW_LINE_HEIGHT = 25
EDIT_IMAGE_HEIGHT_BONUS = 4

# レイアウト関連
DEFAULT_LOGICAL_CENTER_X = 5000
DEFAULT_LOGICAL_CENTER_Y = 5000
CANVAS_MARGIN = 500
NODE_CLICK_PADDING = 10

# デザイン関連
COLOR_TEXT = "#333333"
COLOR_ROOT_OUTLINE = "#222222"
COLOR_ROOT_FILL = "#E3F2FD"
COLOR_HIGHLIGHT_FILL = "#E3F2FD"
COLOR_HIGHLIGHT_OUTLINE = "#2196F3"
COLOR_CANVAS_BG = "#fafafa"

FONT_FAMILY = "Yu Gothic"
FONT_SIZE_NORMAL = 10
FONT_SIZE_ROOT = 12

BRANCH_COLORS = [
    "#FF9D48", # Orange
    "#FF6B6B", # Red
    "#A06EE1", # Purple
    "#4ECDC4", # Teal
    "#5CACE2", # Blue
    "#96CEB4", # Green
]
